In [1]:
import os
import pandas as pd
import numpy as np

In [4]:
os.system("curl -O https://www.foreignlaborcert.doleta.gov/docs/py2015q4/H-1B_Disclosure_Data_FY15_Q4.xlsx")
os.system("mv H-1B_Disclosure_Data_FY15_Q4.xlsx " + os.getenv("PUIDATA"))

0

In [7]:
data = pd.read_excel(os.getenv("PUIDATA") + "/H-1B_Disclosure_Data_FY15_Q4.xlsx")
data.head()

CASE_NUMBER CASE_STATUS CASE_SUBMITTED DECISION_DATE VISA_CLASS  \
0  I-200-09121-701936   WITHDRAWN     2015-02-05    2015-02-05       H-1B   
1  I-200-09146-796321   CERTIFIED     2014-12-12    2014-12-18       H-1B   
2  I-200-09180-329758   WITHDRAWN     2013-01-03    2014-12-15       H-1B   
3  I-200-09183-259985   CERTIFIED     2015-03-10    2015-03-16       H-1B   
4  I-200-09189-800933   CERTIFIED     2014-12-17    2014-12-23       H-1B   

  EMPLOYMENT_START_DATE EMPLOYMENT_END_DATE                    EMPLOYER_NAME  \
0            02/09/2015          02/28/2015                  MEDTRONIC, INC.   
1            01/05/2015          01/04/2018           UNIVERSITY OF OKLAHOMA   
2            01/07/2013          01/06/2016                       NOKIA INC.   
3            09/07/2015          09/07/2018  OMRON OILFIELD AND MARINE, INC.   
4            06/06/2015          06/05/2018   FEDERAL HOME LOAN MORTGAGE CO.   

              EMPLOYER_ADDRESS1 EMPLOYER_ADDRESS2         ...           \
0      710 MEDTRONIC PARKWAY NE               NaN         ...            
1                   905 ASP AVE      NEL BLDG 207         ...            
2         6021 CONNECTION DRIVE               NaN         ...            
3  9510 N. HOUSTON ROSSLYN ROAD               NaN         ...            
4       8250 JONES BRANCH DRIVE             MSA3E         ...            

  PW_WAGE_SOURCE_YEAR     PW_WAGE_SOURCE_OTHER WAGE_RATE_OF_PAY  \
0              2014.0       ONLINE DATA SURVEY          20000 -   
1              2014.0  OFLC ONLINE DATA CENTER       85000.00 -   
2              2012.0  OFLC ONLINE DATA CENTER          94000 -   
3              2014.0  OFLC ONLINE DATA CENTER    66000 - 70000   
4              2014.0  OFLC ONLINE DATA CENTER   97000 - 143300   

  WAGE_UNIT_OF_PAY H-1B_DEPENDENT  WILLFUL VIOLATOR  WORKSITE_CITY  \
0             Year              N                 N   EDEN PRAIRIE   
1             Year              N                 N         NORMAN   
2             Year              N                 N      SAN DIEGO   
3             Year              N                 N        HOUSTON   
4             Year              N                 N         MCLEAN   

  WORKSITE_COUNTY WORKSITE_STATE WORKSITE_POSTAL_CODE  
0          STERNS             CA                55412  
1       CLEVELAND             OK                73019  
2       SAN DIEGO             CA                92127  
3          HARRIS             TX                77088  
4         FAIRFAX             VA                22102  

[5 rows x 40 columns]

In [8]:
data.shape

(618804, 40)

In [75]:
print data.dtypes.values[1]

object


In [49]:
for i, col in enumerate(data.columns):
    print ("%2d : %s"%(i, col))

 0 : CASE_NUMBER
 1 : CASE_STATUS
 2 : CASE_SUBMITTED
 3 : DECISION_DATE
 4 : VISA_CLASS
 5 : EMPLOYMENT_START_DATE
 6 : EMPLOYMENT_END_DATE
 7 : EMPLOYER_NAME
 8 : EMPLOYER_ADDRESS1
 9 : EMPLOYER_ADDRESS2
10 : EMPLOYER_CITY
11 : EMPLOYER_STATE
12 : EMPLOYER_POSTAL_CODE
13 : EMPLOYER_COUNTRY
14 : EMPLOYER_PROVINCE
15 : EMPLOYER_PHONE
16 : EMPLOYER_PHONE_EXT
17 : AGENT_ATTORNEY_NAME
18 : AGENT_ATTORNEY_CITY
19 : AGENT_ATTORNEY_STATE
20 : JOB_TITLE
21 : SOC_CODE
22 : SOC_NAME
23 : NAIC_CODE
24 : TOTAL WORKERS
25 : FULL_TIME_POSITION
26 : PREVAILING_WAGE
27 : PW_UNIT_OF_PAY
28 : PW_WAGE_LEVEL
29 : PW_WAGE_SOURCE
30 : PW_WAGE_SOURCE_YEAR
31 : PW_WAGE_SOURCE_OTHER
32 : WAGE_RATE_OF_PAY
33 : WAGE_UNIT_OF_PAY
34 : H-1B_DEPENDENT
35 : WILLFUL VIOLATOR
36 : WORKSITE_CITY
37 : WORKSITE_COUNTY
38 : WORKSITE_STATE
39 : WORKSITE_POSTAL_CODE


In [76]:
Rcols = [0,1,2,3,5,6,7,20,22,23,24,25,26,27,28,32,33,34,35,36,38,39]

In [17]:
data['VISA_CLASS'].unique()

array([u'H-1B', u'H-1B1 Chile', u'H-1B1 Singapore', u'E-3 Australian'], dtype=object)

In [14]:
data1 = data[data['VISA_CLASS'] == 'H-1B']

In [26]:
data1.shape

(605803, 40)

In [42]:
np.sum(data1['FULL_TIME_POSITION'] == 'Y')

591219

In [52]:
data2 = data1[data1['FULL_TIME_POSITION'] == 'Y']

In [80]:
data3 = data1.iloc[:, Rcols]
data3.shape

(605803, 22)

In [78]:
data3.dtypes

CASE_NUMBER                      object
CASE_STATUS                      object
CASE_SUBMITTED           datetime64[ns]
DECISION_DATE            datetime64[ns]
EMPLOYMENT_START_DATE            object
EMPLOYMENT_END_DATE              object
EMPLOYER_NAME                    object
JOB_TITLE                        object
SOC_NAME                         object
NAIC_CODE                       float64
TOTAL WORKERS                   float64
FULL_TIME_POSITION               object
PREVAILING_WAGE                 float64
PW_UNIT_OF_PAY                   object
PW_WAGE_LEVEL                    object
WAGE_RATE_OF_PAY                 object
WAGE_UNIT_OF_PAY                 object
H-1B_DEPENDENT                   object
WILLFUL VIOLATOR                 object
WORKSITE_CITY                    object
WORKSITE_STATE                   object
WORKSITE_POSTAL_CODE             object
dtype: object

In [85]:
data3.groupby('CASE_STATUS').count()

CASE_NUMBER  CASE_SUBMITTED  DECISION_DATE  \
CASE_STATUS                                                       
CERTIFIED                 536693          536693         536693   
CERTIFIED-WITHDRAWN        40368           40368          40368   
DENIED                      9703            9703           9703   
WITHDRAWN                  19039           19039          19039   

                     EMPLOYMENT_START_DATE  EMPLOYMENT_END_DATE  \
CASE_STATUS                                                       
CERTIFIED                           536693               536693   
CERTIFIED-WITHDRAWN                  40368                40368   
DENIED                                9701                 9701   
WITHDRAWN                            19022                19022   

                     EMPLOYER_NAME  JOB_TITLE  SOC_NAME  NAIC_CODE  \
CASE_STATUS                                                          
CERTIFIED                   536692     536693    536693     536692   
CERTIFIED-WITHDRAWN          40368      40368     40368      40368   
DENIED                        9702       9699      9700       9701   
WITHDRAWN                    19018      19023     19026      19022   

                     TOTAL WORKERS          ...           PREVAILING_WAGE  \
CASE_STATUS                                 ...                             
CERTIFIED                   536693          ...                    536693   
CERTIFIED-WITHDRAWN          40368          ...                     40368   
DENIED                        9702          ...                      9670   
WITHDRAWN                    19025          ...                     19023   

                     PW_UNIT_OF_PAY  PW_WAGE_LEVEL  WAGE_RATE_OF_PAY  \
CASE_STATUS                                                            
CERTIFIED                    536693         513949            536693   
CERTIFIED-WITHDRAWN           40368          37619             40368   
DENIED                         9662           8188              9703   
WITHDRAWN                     19023          18086             19039   

                     WAGE_UNIT_OF_PAY  H-1B_DEPENDENT  WILLFUL VIOLATOR  \
CASE_STATUS                                                               
CERTIFIED                      536693          536693            536693   
CERTIFIED-WITHDRAWN             40368           40368             40368   
DENIED                           9690            9684              9685   
WITHDRAWN                       19023           19023             19023   

                     WORKSITE_CITY  WORKSITE_STATE  WORKSITE_POSTAL_CODE  
CASE_STATUS                                                               
CERTIFIED                   536685          536693                536685  
CERTIFIED-WITHDRAWN          40367           40368                 40366  
DENIED                        9698            9695                  9695  
WITHDRAWN                    19020           19022                 19020  

[4 rows x 21 columns]

In [86]:
data4 = data3[(data3['CASE_STATUS'] == 'CERTIFIED') | (data3['CASE_STATUS'] == 'DENIED')]
data4.shape

(546396, 22)

In [87]:
np.sum(data4["FULL_TIME_POSITION"] == 'Y')

533015

In [88]:
data4['PW_UNIT_OF_PAY'].unique()

array([u'Year', u'Hour', u'Week', u'Month', nan, u'Bi-Weekly'], dtype=object)

In [90]:
data4['WAGE_UNIT_OF_PAY'].unique()

array([u'Year', u'Hour', u'Week', u'Month', u'Bi-Weekly', nan], dtype=object)

In [117]:
data5 = data4.dropna(subset = ['PW_UNIT_OF_PAY', 'WAGE_UNIT_OF_PAY', 
                               'PREVAILING_WAGE', 'WAGE_RATE_OF_PAY', 'FULL_TIME_POSITION'])
data5.shape

(546345, 22)

In [115]:
def convertwage(wage, unit, FT):
    if unit == 'Year':
        return wage
    elif unit == 'Month':
        return wage * 12
    elif unit == 'Week':
        return wage * 4 *12
    elif unit == 'Bi-Weekly':
        return wage * 2 * 12
    elif unit == 'Hour':
        if FT == 'Y':
            return wage * 40 * 4 * 12
        elif FT == 'N':
            return wage * 20 * 4 * 12
Convertwage = np.vectorize(convertwage)

In [148]:
def rangeconvert(w_str):
    w_list = np.array(w_str.split("-"))
    try:
        return (w_list[0].astype(float) + w_list[1].astype(float)) / 2
    except ValueError:
        return w_list[0].astype(float)
Rangeconvert = np.vectorize(rangeconvert)

In [118]:
Convertwage(data5['PREVAILING_WAGE'], data5['PW_UNIT_OF_PAY'], data5['FULL_TIME_POSITION'])

array([  42860.,   65998.,   96907., ...,   51272.,   80704.,  178381.])

In [149]:
Rangeconvert(data5['WAGE_RATE_OF_PAY'])

array([  85000.,   68000.,  120150., ...,   55000.,   85000.,  225000.])

In [150]:
Convertwage(Rangeconvert(data5['WAGE_RATE_OF_PAY']), data5['WAGE_UNIT_OF_PAY'], data5['FULL_TIME_POSITION'])

array([  85000.,   68000.,  120150., ...,   55000.,   85000.,  225000.])

In [151]:
data5['PW_WAGE_annual'] = Convertwage(data5['PREVAILING_WAGE'], data5['PW_UNIT_OF_PAY'], data5['FULL_TIME_POSITION'])
data5['WAGE_annual'] = Convertwage(Rangeconvert(data5['WAGE_RATE_OF_PAY']), 
                                   data5['WAGE_UNIT_OF_PAY'], data5['FULL_TIME_POSITION'])

/opt/rh/anaconda/root/envs/PUI2016_Python2/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/opt/rh/anaconda/root/envs/PUI2016_Python2/lib/python2.7/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()


In [154]:
data5.dtypes

CASE_NUMBER                      object
CASE_STATUS                      object
CASE_SUBMITTED           datetime64[ns]
DECISION_DATE            datetime64[ns]
EMPLOYMENT_START_DATE            object
EMPLOYMENT_END_DATE              object
EMPLOYER_NAME                    object
JOB_TITLE                        object
SOC_NAME                         object
NAIC_CODE                       float64
TOTAL WORKERS                   float64
FULL_TIME_POSITION               object
PREVAILING_WAGE                 float64
PW_UNIT_OF_PAY                   object
PW_WAGE_LEVEL                    object
WAGE_RATE_OF_PAY                 object
WAGE_UNIT_OF_PAY                 object
H-1B_DEPENDENT                   object
WILLFUL VIOLATOR                 object
WORKSITE_CITY                    object
WORKSITE_STATE                   object
WORKSITE_POSTAL_CODE             object
PW_WAGE_annual                  float64
WAGE_annual                     float64
dtype: object

In [167]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

In [156]:
def status(S):
    if S == 'CERTIFIED':
        return 1
    else:
        return 0
Status = np.vectorize(status)

In [159]:
def dep(D):
    if D == 'Y':
        return 1
    else:
        return 0
Dep = np.vectorize(dep)

In [165]:
Rdata = data5.loc[:,['PW_WAGE_annual', 'WAGE_annual', 'NAIC_CODE', 'TOTAL WORKERS', 
                     'H-1B_DEPENDENT', 'CASE_STATUS']].dropna()
Y = Status(Rdata['CASE_STATUS'])
#X = Rdata.loc[:,['PW_WAGE_annual', 'WAGE_annual', 'NAIC_CODE', 'TOTAL WORKERS']]
#X['H-1B_DEPENDENT'] = Dep(Rdata['H-1B_DEPENDENT'])
X = Rdata.loc[:,['PW_WAGE_annual', 'WAGE_annual']]

In [195]:
X = Rdata.loc[:,['PW_WAGE_annual', 'WAGE_annual']]

In [196]:
n = len(Y) / 2
logreg = LogisticRegression(C = 1e6)
logreg.fit(X, Y)

LogisticRegression(C=1000000.0, class_weight=None, dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)

In [197]:
label  = logreg.predict(X)
M = confusion_matrix(label, Y)
print M

[[    71      2]
 [  9571 536690]]


In [189]:
M[1,0]

4768

In [198]:
print (M[0,0] + M[1,1]) / float(M.sum())

0.982477751705


In [199]:
print ('Fitted parameters:')
print ("  Intercept : {}".format(logreg.intercept_))
print ("  Coefficient : {}".format(logreg.coef_))

Fitted parameters:
  Intercept : [  1.20369910e-09]
  Coefficient : [[ -5.41783653e-08   4.67181702e-05]]


In [203]:
logreg.coef_[0][0] * np.mean(X.iloc[:,0])

-0.0047980886572631812

In [204]:
logreg.coef_[0][1] * np.mean(X.iloc[:,1])

4.0266221383404677

In [210]:
logreg.predict_proba(X)[:,1]

array([ 0.98145293,  0.95981551,  0.99634478, ...,  0.92868888,
        0.98141557,  0.99997252])

In [211]:
np.sum(data5['CASE_STATUS'] == 'CERTIFIED')

536693

In [212]:
np.sum(data5['CASE_STATUS'] == 'DENIED')

9652